version: '3'
services:
  tex4tum:
    build: .
    volumes:
      - ..:/srv/jekyll
    environment:
      JEKYLL_ENV: production
    ports:
      - '4000:4000'
    command: bash -c "pandoc -v && bundle install && bundle exec jekyll serve --host 0.0.0.0"
